### ISSUE TITLE
Doesn't work for me in nvim v0.4.3

### ISSUE THREAD

**Issue by mehant-kr** [gennaro-tedesco/nvim-commaround#1]
Doesn't do anything when I `<leader>c` in visual mode instead I get the following error
[Image](https://imgur.com/a/t0IO710)

**Comment by gennaro-tedesco** [comment]
The error is presumably caused by the fact that `vim.bo.filetype` returns `nil` (in particular the call to `vim.bo`).

In order to debug it

1. please issue the command `:lua print(vim.bo.filetype)` and check the output. This should return the filetype of the current buffer: does it return the correct value (or any non-nil value)?
2. what version of neovim are you running? I suspect that the API `vim.bo.filetype` needs latest [nightly build](https://github.com/neovim/neovim/releases/tag/nightly) and I believe the error is caused by such property call returning a null value.
3. in order to validate assumption 2. you may try to replace the call to `vim.bo.filetype` with the hardcoded value of a specific filetype (just for testing). Say replace in the code `local filetype_config = global_config.config['lua']` and toggle comments on a Lua file: if the plugin works fine by passing the reference manually, then the problem is indeed as point 2 above; otherwise it is a bug and I will investigate.

**Comment by mehant-kr** [comment]
Same error with ```:lua print(vim.bo.filetype)``` 
Done as stated in 3 and got an error [https://imgur.com/a/PSNWTYL](image)
I am using nvim v0.4.3 though it works on nvim v0.5.0, I installed nightly build and now it works fine for me.

**Comment by gennaro-tedesco** [comment]
I will update the README file to specify that the nightly build is indeed recommended (I did not realise it myself before you pointed it out, so good to have looked into it).
